# File generated by CompCert 3.5
# Command line: -dasm src/empty_struct.c -o build/empty_struct
	.comm	e, 0, 1
	.text
	.align	16
	.globl main
main:
	.cfi_startproc
[debug]	Pfreeframe
	xorl	%eax, %eax
[debug]	Pfreeframe
	ret
	.cfi_endproc
	.type	main, @function
	.size	main, . - main
