# File generated by CompCert 3.5
# Command line: -dasm src/empty_struct.c -o build/empty_struct
	.comm	e, 0, 1
	.text
	.align	16
	.globl main
main:
	.cfi_startproc
	subq	$8, %rsp
	leaq	16(%rsp), %rax
	movq	%rax, 0(%rsp)
	xorl	%eax, %eax
	addq	$8, %rsp
	ret
	.cfi_endproc
	.type	main, @function
	.size	main, . - main
