# File generated by CompCert 3.5
# Command line: -dasm test_lib2.c -c -o bin2
	.text
	.align	16
	.globl extr
extr:
	.cfi_startproc
[debug]	Pfreeframe
	movq	%rbx, 8(%rsp)
	movq	%rbp, 16(%rsp)
	movq	%r12, 24(%rsp)
	movq	%r13, 32(%rsp)
	movl	40(%rax), %r12d
	movl	32(%rax), %ebp
	movl	24(%rax), %r11d
	movl	16(%rax), %r10d
	movl	8(%rax), %ebx
	movl	0(%rax), %r13d
	leal	0(%edi,%esi,1), %eax
	leal	0(%eax,%edx,1), %edx
	leal	0(%edx,%ecx,1), %eax
	leal	0(%eax,%r8d,1), %r8d
	leal	0(%r8d,%r9d,1), %eax
	leal	0(%eax,%r13d,1), %edx
	leal	0(%edx,%ebx,1), %eax
	leal	0(%eax,%r10d,1), %esi
	leal	0(%esi,%r11d,1), %r9d
	leal	0(%r9d,%ebp,1), %ecx
	leal	0(%ecx,%r12d,1), %eax
	movq	8(%rsp), %rbx
	movq	16(%rsp), %rbp
	movq	24(%rsp), %r12
	movq	32(%rsp), %r13
[debug]	Pfreeframe
	ret
	.cfi_endproc
	.type	extr, @function
	.size	extr, . - extr
	.text
	.align	16
	.globl main
main:
	.cfi_startproc
[debug]	Pfreeframe
	movq	%rbx, 56(%rsp)
	movq	%rbp, 64(%rsp)
	movq	%r12, 72(%rsp)
	movq	%r13, 80(%rsp)
	movl	$1, %edi
	movl	$2, %esi
	movl	$3, %edx
	movl	$4, %ecx
	movl	$5, %r8d
	movl	$6, %r9d
	movl	$7, %eax
	movl	$8, %r12d
	movl	$9, %ebx
	movl	$10, %ebp
	movl	$11, %r13d
	movl	$12, %r10d
	movl	%r10d, 40(%rsp)
	movl	%r13d, 32(%rsp)
	movl	%ebp, 24(%rsp)
	movl	%ebx, 16(%rsp)
	movl	%r12d, 8(%rsp)
	movl	%eax, 0(%rsp)
	call	extr
	xorl	%eax, %eax
	movq	56(%rsp), %rbx
	movq	64(%rsp), %rbp
	movq	72(%rsp), %r12
	movq	80(%rsp), %r13
[debug]	Pfreeframe
	ret
	.cfi_endproc
	.type	main, @function
	.size	main, . - main
