# File generated by CompCert 3.5
# Command line: -dasm -c -o test_obj.o test_lib.c
	.text
	.align	16
	.globl extr
extr:
	.cfi_startproc
[debug]	Pfreeframe
	leal	0(%edi,%esi,1), %eax
[debug]	Pfreeframe
	ret
	.cfi_endproc
	.type	extr, @function
	.size	extr, . - extr
