# File generated by CompCert 3.5
# Command line: example_object.c -dasm -c -o tests/src/object_files/example_object.o
	.text
	.align	16
	.globl bar
bar:
	.cfi_startproc
	subq	$8, %rsp
	.cfi_adjust_cfa_offset	8
	leaq	16(%rsp), %rax
	movq	%rax, 0(%rsp)
	xorl	%eax, %eax
	xorl	%ecx, %ecx
.L100:
	cmpl	%edi, %ecx
	jge	.L101
	leal	0(%eax,%ecx,1), %eax
	leal	1(%ecx), %ecx
	jmp	.L100
.L101:
	addq	$8, %rsp
	ret
	.cfi_endproc
	.type	bar, @function
	.size	bar, . - bar
	.text
	.align	16
	.globl foo
foo:
	.cfi_startproc
	subq	$24, %rsp
	.cfi_adjust_cfa_offset	24
	leaq	32(%rsp), %rax
	movq	%rax, 0(%rsp)
	movq	%rbx, 8(%rsp)
	movq	%rsi, %rbx
	call	bar
	leal	0(%eax,%ebx,1), %eax
	movq	8(%rsp), %rbx
	addq	$24, %rsp
	ret
	.cfi_endproc
	.type	foo, @function
	.size	foo, . - foo
