# File generated by CompCert 3.5
# Command line: -dasm fun_test.c -c -o bin2
	.section	.rodata
	.align	1
__stringlit_1:
	.ascii	"%d\012\000"
	.type	__stringlit_1, @object
	.size	__stringlit_1, . - __stringlit_1
	.text
	.align	16
	.globl foo
foo:
	.cfi_startproc
	subq	$8, %rsp
	leaq	16(%rsp), %rax
	movq	%rax, 0(%rsp)
	leal	0(%edi,%esi,1), %eax
	addq	$8, %rsp
	ret
	.cfi_endproc
	.type	foo, @function
	.size	foo, . - foo
	.text
	.align	16
	.globl main
main:
	.cfi_startproc
	subq	$8, %rsp
	leaq	16(%rsp), %rax
	movq	%rax, 0(%rsp)
	movl	$1, %edi
	movl	$2, %esi
	call	foo
	movq	%rax, %rsi
	leaq	__stringlit_1(%rip), %rdi
	movl	$0, %eax
	call	printf
	xorl	%eax, %eax
	addq	$8, %rsp
	ret
	.cfi_endproc
	.type	main, @function
	.size	main, . - main
