# File generated by CompCert 3.5
# Command line: -dasm test_lib.c
	.text
	.align	16
	.globl extr
extr:
	.cfi_startproc
	subq	$8, %rsp
	leaq	16(%rsp), %rax
	movq	%rax, 0(%rsp)
	movq	%rdi, %rax
	subl	%esi, %eax
	addq	$8, %rsp
	ret
	.cfi_endproc
	.type	extr, @function
	.size	extr, . - extr
	.text
	.align	16
	.globl main
main:
	.cfi_startproc
	subq	$8, %rsp
	leaq	16(%rsp), %rax
	movq	%rax, 0(%rsp)
	movl	$2, %edi
	movl	$3, %esi
	call	extr
	xorl	%eax, %eax
	addq	$8, %rsp
	ret
	.cfi_endproc
	.type	main, @function
	.size	main, . - main
