# File generated by CompCert 3.5
# Command line: -dasm -c -o test_obj.o test_lib.c
	.text
	.align	16
	.globl extr
extr:
	.cfi_startproc
	subq	$8, %rsp
	leaq	16(%rsp), %rax
	movq	%rax, 0(%rsp)
	leal	0(%edi,%esi,1), %esi
	leal	0(%esi,%edx,1), %edx
	leal	0(%edx,%ecx,1), %eax
	addq	$8, %rsp
	ret
	.cfi_endproc
	.type	extr, @function
	.size	extr, . - extr
