# File generated by CompCert 3.5
# Command line: example_object.c -dasm -c -o example_object.o
	.text
	.align	16
	.globl bar
bar:
	.cfi_startproc
	subq	$24, %rsp
	.cfi_adjust_cfa_offset	24
	leaq	32(%rsp), %rax
	movq	%rax, 0(%rsp)
	movq	%rbx, 8(%rsp)
	movslq	%edi, %rax
	leaq	0(,%rax,4), %rdi
	call	malloc
	movq	%rax, %rdi
	movl	$1, %ebx
	movl	%ebx, 0(%rdi)
	call	free
	movq	%rbx, %rax
	movq	8(%rsp), %rbx
	addq	$24, %rsp
	ret
	.cfi_endproc
	.type	bar, @function
	.size	bar, . - bar
	.text
	.align	16
	.globl foo
foo:
	.cfi_startproc
	subq	$24, %rsp
	.cfi_adjust_cfa_offset	24
	leaq	32(%rsp), %rax
	movq	%rax, 0(%rsp)
	movq	%rbx, 8(%rsp)
	movq	%rsi, %rbx
	call	bar
	leal	0(%eax,%ebx,1), %eax
	movq	8(%rsp), %rbx
	addq	$24, %rsp
	ret
	.cfi_endproc
	.type	foo, @function
	.size	foo, . - foo
