# File generated by CompCert 3.5
# Command line: global.c -dasm -c -o global.o
	.comm	x, 4, 4
	.text
	.align	16
	.globl foo
foo:
	.cfi_startproc
	subq	$8, %rsp
	.cfi_adjust_cfa_offset	8
	leaq	16(%rsp), %rax
	movq	%rax, 0(%rsp)
	movl	$4, %eax
	movl	%eax, x(%rip)
	movl	$4, %eax
	addq	$8, %rsp
	ret
	.cfi_endproc
	.type	foo, @function
	.size	foo, . - foo
