# File generated by CompCert 3.5
# Command line: -dasm recursive.c -c -o recursive2.o
	.text
	.align	16
	.globl factorial
factorial:
	.cfi_startproc
	subq	$24, %rsp
	.cfi_adjust_cfa_offset	24
	leaq	32(%rsp), %rax
	movq	%rax, 0(%rsp)
	movq	%rbx, 8(%rsp)
	movq	%rdi, %rbx
	cmpl	$1, %ebx
	jg	.L100
	movl	$1, %ebx
	jmp	.L101
.L100:
	leal	-1(%ebx), %edi
	call	factorial
	imull	%eax, %ebx
.L101:
	movq	%rbx, %rax
	movq	8(%rsp), %rbx
	addq	$24, %rsp
	ret
	.cfi_endproc
	.type	factorial, @function
	.size	factorial, . - factorial
